Feat(personen overlay)
JOTTMEDIA/jottmedia.github.io pull request #6
Opened 2024-07-09 16:59 UTC by c1chy-jott

Check Personen overlay slugs and layout

2024-07-10 08:53 UTC, JonathanSchndr requested changes

2024-07-10 08:53 UTC, JonathanSchndr commented on components/ImageFigure.vue
> +      </NuxtLink>
This is not linked correctly. The whole image should not be linked, but the + in the circle. Please check your layout again.

2024-07-10 08:53 UTC, JonathanSchndr commented on pages/index.vue
> +                  <ImageFigure  to="/team/inke"  src="inke.jpg" hint="Inke // Finanzen" align="left">„<b class="text-jm-primary-brown">Obwohl</b> in meiner Schulzeit zuerst die <b>Mengenlehre</b> unt
Can you build this so that this display is automatically generated from all Markdown files of content/team?

2024-07-10 08:53 UTC, JonathanSchndr commented on pages/team/[...slug].vue
> +</script>
The Close button at the top right is still missing to return to the previous page. History back must be executed.
In addition, you can currently scroll on the page and the footer is included. This should not be the case, as it should feel like an overlay

2024-07-10 08:53 UTC, JonathanSchndr commented
In addition, the link on the blog author's name to the team page is still missing.

2024-07-10 16:48 UTC, c1chy-jott commented
> In addition, the link on the blog author's name to the team page is still missing.

i cant change it because i dont have actual blog on this branch ....

2024-07-10 16:50 UTC, c1chy-jott commented
I have some problem with Layout/Page transition it doesn't work correctly

2024-07-11 06:29 UTC, JonathanSchndr commented
- Currently I get a 500 error on the start page, therefore 404 is displayed

The team MD files are not correct, not everything is there yet and seoTitle is "Was"
You and Alex are still missing as MD files, please create them so far
I have merged the current master into the branch. Can you please fix it today, besides the other THemen?

2024-07-11 06:29 UTC, JonathanSchndr requested changes
- Currently I get a 500 error on the start page, therefore 404 is displayed

The team MD files are not correct, not everything is there yet and seoTitle is "What"
You and Alex are still missing as MD files, please create them so far
I have merged the current master into the branch. Can you please fix it today, besides the other THemen?

2024-07-12 15:46 UTC, c1chy-jott commented
![](https://github.trello.services/images/mini-trello-icon.png) [[JOTT.MEDIA]: Personen Layout](https://trello.com/c/83RW6XiB/10-jottmedia-personen-layout)

2024-09-13 09:42 UTC, merged